# Generated by Django 3.2.16 on 2022-12-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('slogan', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='site/info')),
                ('contact_1', models.CharField(max_length=150)),
                ('contact_2', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=155)),
                ('adresse', models.TextField()),
                ('map_url', models.TextField()),
                ('facebook_url', models.TextField()),
                ('instagram_url', models.TextField()),
                ('twitter_url', models.TextField()),
                ('whatsapp', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
