# Generated by Django 3.2.16 on 2024-10-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListeSouhait',
        ),
    ]
