# Generated by Django 3.2.16 on 2022-12-11 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePromotionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('etat', models.BooleanField()),
                ('date_fin', models.DateField()),
                ('reduction', models.FloatField()),
                ('nombre_u', models.PositiveIntegerField(null=True)),
                ('code_promo', models.CharField(max_length=150)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('forfait', models.ManyToManyField(blank=True, related_name='produit_code_promo', to='shop.Produit')),
            ],
            options={
                'verbose_name': 'Code promotionnel',
                'verbose_name_plural': 'Codes Promotionnels',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.TextField()),
                ('photo', models.ImageField(upload_to='clients/photo')),
                ('contact_1', models.CharField(max_length=15)),
                ('contact_2', models.CharField(max_length=15)),
                ('ville', models.CharField(max_length=155)),
                ('pays', models.CharField(max_length=155)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_use', to='customer.codepromotionnel')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_panier', to='customer.customer')),
                ('produit', models.ManyToManyField(related_name='panier', to='shop.Produit')),
                ('session_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_panier', to='sessions.session')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paiment', models.CharField(max_length=50, null=True)),
                ('crypto', models.CharField(max_length=50, null=True)),
                ('prix_total', models.FloatField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('recu_paiement', models.FileField(null=True, upload_to='fichiers/paiements')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_commande', to='customer.customer')),
                ('produit', models.ManyToManyField(related_name='commande', to='shop.Produit')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
    ]
