# Generated by Django 3.2.16 on 2022-12-19 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20221219_1732'),
        ('customer', '0002_auto_20221219_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='produit',
        ),
        migrations.CreateModel(
            name='ProduitPanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('commande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit_commande', to='customer.commande')),
                ('panier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit_panier', to='customer.panier')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande', to='shop.produit')),
            ],
            options={
                'verbose_name': 'Produit Panier/Commande',
                'verbose_name_plural': 'Produits Panier/Commande',
            },
        ),
    ]
