# Generated by Django 3.2.16 on 2023-02-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20221219_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='api_response_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='payment_token',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='payment_url',
            field=models.TextField(null=True),
        ),
    ]
