# Generated by Django 5.1.2 on 2024-11-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20230207_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='transaction_id',
            field=models.TextField(null=True),
        ),
    ]
