# Generated by Django 4.2.9 on 2025-09-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ville',
        ),
    ]
