# Generated by Django 4.2.9 on 2025-09-06 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0012_city_translations_country_translations_and_more'),
        ('customer', '0007_remove_customer_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city'),
        ),
    ]
