# Generated by Django 3.2.16 on 2022-12-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=254)),
                ('sous_titre', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='media/bannieres')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Session A propos',
                'verbose_name_plural': 'Sessions A propos',
            },
        ),
        migrations.CreateModel(
            name='Appreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Banniere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('couverture', models.ImageField(null=True, upload_to='media/bannieres')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Galerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='media/bannieres')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('slogan', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='site/info')),
                ('arriere_plan_appreciation', models.ImageField(upload_to='site/info')),
                ('image_session_pourquoi_nous_choisir', models.ImageField(upload_to='site/info')),
                ('image_page_contact', models.ImageField(upload_to='site/info')),
                ('contact_1', models.CharField(max_length=150)),
                ('contact_2', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=155)),
                ('adresse', models.TextField()),
                ('map_url', models.TextField()),
                ('facebook_url', models.TextField()),
                ('instagram_url', models.TextField()),
                ('twitter_url', models.TextField()),
                ('whatsapp', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('zmdi-favorite', 'zmdi-favorite'), ('fa-pagelines', 'fa-pagelines'), ('zmdi-mood', 'zmdi-mood'), ('zmdi-dribbble', 'zmdi-dribbble')], max_length=254)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pourquoi Nous choisir',
            },
        ),
    ]
