# Generated by Django 3.2.16 on 2022-12-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_siteinfo_email_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='image_pied_de_page',
            field=models.ImageField(null=True, upload_to='site/info'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='text_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
