# Generated by Django 3.2.16 on 2022-12-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20221219_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinfo',
            old_name='text_description',
            new_name='horaire_description',
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='logo',
            field=models.ImageField(default='logo.png', upload_to='site/info'),
        ),
    ]
