# Generated by Django 3.2.16 on 2022-12-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_partenaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='appreciation',
            name='auteur',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appreciation',
            name='role',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='text_pourquoi_nous_choisir',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
