# Generated by Django 3.2.16 on 2022-12-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20221220_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='couverture',
            field=models.ImageField(null=True, upload_to='media/bannieres'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='couverture_page_contact',
            field=models.ImageField(null=True, upload_to='site/info'),
        ),
    ]
