# Generated by Django 3.2.16 on 2022-12-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20221220_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='couverture_page_paiement',
            field=models.ImageField(null=True, upload_to='site/info'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='couverture_page_panier',
            field=models.ImageField(null=True, upload_to='site/info'),
        ),
    ]
