# Generated by Django 3.2.16 on 2022-12-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20221220_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='couverture',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='couverture_page_about',
            field=models.ImageField(null=True, upload_to='site/info'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='couverture_page_shop',
            field=models.ImageField(null=True, upload_to='site/info'),
        ),
    ]
