# Generated by Django 3.2.16 on 2023-01-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20221220_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='arriere_plan_appreciation_2',
            field=models.ImageField(null=True, upload_to='site/info'),
        ),
    ]
