# Generated by Django 3.2.16 on 2023-02-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_siteinfo_arriere_plan_appreciation_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='icon',
            field=models.ImageField(default='icon.png', upload_to='site/info'),
        ),
    ]
