# Generated by Django 3.2.16 on 2022-12-13 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_categorieproduit_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='categorie_etab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit_etab', to='shop.categorieetablissement'),
        ),
    ]
