# Generated by Django 3.2.16 on 2022-12-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_produit_categorie_etab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='site_web',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
