# Generated by Django 3.2.16 on 2022-12-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_etablissement_site_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='site_web',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
