# Generated by Django 3.2.16 on 2022-12-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_etablissement_site_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(default='b-1.jpg', upload_to='produis/images'),
        ),
    ]
