# Generated by Django 3.2.16 on 2022-12-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='date_debut_promo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_fin_promo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_promotionnel',
            field=models.FloatField(default=0),
        ),
    ]
