# Generated by Django 3.2.16 on 2022-12-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20221213_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieetablissement',
            name='couverture',
            field=models.ImageField(null=True, upload_to='media/categories/etablissements/couvertures'),
        ),
        migrations.AddField(
            model_name='categorieproduit',
            name='couverture',
            field=models.ImageField(null=True, upload_to='media/categories/produits/couvertures'),
        ),
    ]
