# Generated by Django 3.2.16 on 2022-12-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20221219_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image_2',
            field=models.ImageField(default='b-1.jpg', upload_to='produis/images'),
        ),
        migrations.AddField(
            model_name='produit',
            name='image_3',
            field=models.ImageField(default='b-1.jpg', upload_to='produis/images'),
        ),
    ]
