# Generated by Django 3.2.16 on 2022-12-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20221219_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='super_deal',
            field=models.BooleanField(default=False),
        ),
    ]
