# Generated by Django 3.2.16 on 2024-10-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_produit_super_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='code_acces',
            field=models.CharField(default='12345678@@', max_length=100),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='nom_du_responsable',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='prenoms_duresponsable',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
