# Generated by Django 4.2.9 on 2024-12-06 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0012_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='etablissement', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
