# Generated by Django 4.2.9 on 2025-09-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_etablissement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='contact_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
