# Generated by Django 4.2.9 on 2025-09-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_etablissement_contact_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etablissement',
            name='ville',
        ),
    ]
